// templates/nui-svelte/web/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { useNuiEvent, closeNui } from './nui-bridge';

  let visible = $state(false);

  let cleanup: (() => void) | undefined;

  onMount(() => {
    cleanup = useNuiEvent('open', () => {
      visible = true;
    });

    useNuiEvent('close', () => {
      visible = false;
    });

    const handleKeydown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        visible = false;
        closeNui();
      }
    };
    document.addEventListener('keydown', handleKeydown);

    return () => {
      document.removeEventListener('keydown', handleKeydown);
    };
  });

  onDestroy(() => {
    cleanup?.();
  });
</script>

{#if visible}
  <div class="overlay">
    <div class="panel">
      <h1>My Resource</h1>
      <p>Svelte 5 NUI template</p>
      <button onclick={() => { visible = false; closeNui(); }}>Close</button>
    </div>
  </div>
{/if}

<style>
  .overlay {
    position: fixed;
    inset: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    background: rgba(0, 0, 0, 0.5);
  }
  .panel {
    background: #1a1a2e;
    border-radius: 8px;
    padding: 2rem;
    min-width: 320px;
    text-align: center;
  }
  h1 { margin-bottom: 0.5rem; }
  button {
    margin-top: 1rem;
    padding: 0.5rem 1.5rem;
    border: none;
    border-radius: 4px;
    background: #e94560;
    color: #fff;
    cursor: pointer;
    font-size: 1rem;
  }
  button:hover { background: #c73a54; }
</style>

// templates/nui-vite/web/src/App.tsx
import { useEffect, useState } from 'react';
import { useNuiEvent, closeNui, fetchNui } from './nui-bridge';

export default function App() {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const removeOpen = useNuiEvent('open', () => setVisible(true));
    const removeClose = useNuiEvent('close', () => setVisible(false));

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setVisible(false);
        closeNui();
      }
    };
    window.addEventListener('keydown', handleKeyDown);

    return () => {
      removeOpen();
      removeClose();
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, []);

  if (!visible) return null;

  return (
    <div style={styles.overlay}>
      <div style={styles.container}>
        <header style={styles.header}>
          <h2>My Resource</h2>
          <button onClick={() => { setVisible(false); closeNui(); }} style={styles.closeBtn}>
            X
          </button>
        </header>
        <main style={styles.main}>
          <p>Your UI content goes here.</p>
          <button
            style={styles.actionBtn}
            onClick={async () => {
              const result = await fetchNui('getData');
              console.log('Got data:', result);
            }}
          >
            Fetch Data
          </button>
        </main>
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(0, 0, 0, 0.5)',
  },
  container: {
    width: 480,
    maxHeight: '80vh',
    background: '#1a1a2e',
    borderRadius: 12,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderBottom: '1px solid rgba(255,255,255,0.1)',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: '#aaa',
    fontSize: 18,
    cursor: 'pointer',
  },
  main: {
    padding: 20,
    overflowY: 'auto' as const,
    flex: 1,
  },
  actionBtn: {
    marginTop: 16,
    padding: '10px 20px',
    background: '#e94560',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
  },
};
